<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>UltrasoundApp.Dicom</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="fo-dicom" Version="5.1.2" />
    <PackageReference Include="fo-dicom.Imaging.ImageSharp" Version="5.1.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UltrasoundApp.Core\UltrasoundApp.Core.csproj" />
  </ItemGroup>

</Project>
