using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using UltrasoundApp.Core.Logging;

namespace UltrasoundApp.Printing;

/// <summary>
/// One patient-information box the operator placed on the uploaded "Image
/// Template" page (Settings -> Select Image Area -> "Patient information"
/// dropdown): e.g. a box in the header that prints the patient's name.
///
/// <para>
/// Like <see cref="ImageTemplateContentArea"/>, the position and size are
/// <b>fractions of the page (0..1)</b> measured from the top-left corner, so
/// the same saved box works in the Settings editor, in the live preview at
/// any zoom, and in the real PDF composed at print time
/// (<see cref="ImageSheetComposer"/>). The box only says WHERE the text goes;
/// its font size (points), font family and colour are separate settings.
/// </para>
/// </summary>
public sealed class ImageTemplatePlaceholder
{
    /// <summary>Smallest width (page fraction) that is accepted.</summary>
    public const double MinimumWidth = 0.02;

    /// <summary>Smallest height (page fraction) that is accepted.</summary>
    public const double MinimumHeight = 0.008;

    /// <summary>Font size limits in points (same as the editor's).</summary>
    public const double MinimumFontSize = 4;
    public const double MaximumFontSize = 72;

    /// <summary>Unique id of this box (generated by the frontend editor).</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Which patient/study value the box prints — a key such as
    /// <c>patientName</c>, <c>patientId</c>, <c>age</c>, <c>sex</c>. The list of
    /// keys lives in the frontend (placeholderFields.ts); the host only uses
    /// the key to look the text up in the values it is given at print time.
    /// </summary>
    [JsonPropertyName("field")]
    public string Field { get; set; } = string.Empty;

    [JsonPropertyName("x")]
    public double X { get; set; }

    [JsonPropertyName("y")]
    public double Y { get; set; }

    [JsonPropertyName("width")]
    public double Width { get; set; }

    [JsonPropertyName("height")]
    public double Height { get; set; }

    [JsonPropertyName("bold")]
    public bool Bold { get; set; }

    /// <summary>"left", "center" or "right".</summary>
    [JsonPropertyName("align")]
    public string Align { get; set; } = "left";

    /// <summary>
    /// Font size in points. 0 = not set (placeholders saved by the first
    /// version): the composer then derives the size from the box height.
    /// </summary>
    [JsonPropertyName("fontSize")]
    public double FontSize { get; set; }

    /// <summary>Font family name (e.g. "Arial"); empty = the composer's default fonts.</summary>
    [JsonPropertyName("fontFamily")]
    public string FontFamily { get; set; } = string.Empty;

    /// <summary>Text colour as "#RRGGBB".</summary>
    [JsonPropertyName("color")]
    public string Color { get; set; } = "#000000";

    /// <summary>True when the box has a field and describes a usable rectangle that lies inside the page.</summary>
    [JsonIgnore]
    public bool IsValid =>
        !string.IsNullOrWhiteSpace(Field)
        && !double.IsNaN(X) && !double.IsNaN(Y) && !double.IsNaN(Width) && !double.IsNaN(Height)
        && X >= 0 && Y >= 0
        && Width >= MinimumWidth && Height >= MinimumHeight
        && X + Width <= 1.0001 && Y + Height <= 1.0001;
}

/// <summary>
/// Saves / loads the operator's <see cref="ImageTemplatePlaceholder"/> list as
/// a small JSON file (<c>placeholders.json</c>) in the same
/// <c>data/image-templates</c> folder as the uploaded template PDF and its
/// <c>content-area.json</c> — so it survives app restarts and can be
/// re-edited at any time, with no database change.
/// </summary>
public static class ImageTemplatePlaceholderStore
{
    private const string LogCategory = "PRINT";
    private const string FileName = "placeholders.json";

    /// <summary>Sanity cap so a broken frontend can't write an absurd file.</summary>
    private const int MaxPlaceholders = 60;

    private static readonly Regex HexColor = new("^#[0-9a-fA-F]{6}$", RegexOptions.Compiled);

    /// <summary>Letters, digits, spaces and a few punctuation marks — enough for any Windows font name.</summary>
    private static readonly Regex SafeFontName = new(@"^[\p{L}\p{N} .\-_]{1,60}$", RegexOptions.Compiled);

    private static string GetFilePath() => Path.Combine(PrintingPaths.GetImageTemplatesDirectory(), FileName);

    /// <summary>
    /// Cleans up the raw list sent by the frontend: drops unusable entries,
    /// clamps every box into the page, fills in missing ids and normalizes the
    /// alignment.
    /// </summary>
    public static List<ImageTemplatePlaceholder> Normalize(IEnumerable<ImageTemplatePlaceholder>? raw)
    {
        var result = new List<ImageTemplatePlaceholder>();
        if (raw is null)
        {
            return result;
        }

        var usedIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var item in raw)
        {
            if (item is null || result.Count >= MaxPlaceholders)
            {
                continue;
            }

            if (string.IsNullOrWhiteSpace(item.Field)
                || double.IsNaN(item.X) || double.IsNaN(item.Y) || double.IsNaN(item.Width) || double.IsNaN(item.Height))
            {
                continue;
            }

            double width = Math.Clamp(item.Width, ImageTemplatePlaceholder.MinimumWidth, 1);
            double height = Math.Clamp(item.Height, ImageTemplatePlaceholder.MinimumHeight, 1);
            double x = Math.Clamp(item.X, 0, 1 - width);
            double y = Math.Clamp(item.Y, 0, 1 - height);

            string id = string.IsNullOrWhiteSpace(item.Id) ? Guid.NewGuid().ToString("N") : item.Id.Trim();
            if (!usedIds.Add(id))
            {
                id = Guid.NewGuid().ToString("N");
                usedIds.Add(id);
            }

            string align = (item.Align ?? string.Empty).Trim().ToLowerInvariant() switch
            {
                "center" => "center",
                "right" => "right",
                _ => "left",
            };

            double fontSize = double.IsNaN(item.FontSize) || item.FontSize <= 0
                ? 0
                : Math.Clamp(item.FontSize, ImageTemplatePlaceholder.MinimumFontSize, ImageTemplatePlaceholder.MaximumFontSize);
            string fontFamily = (item.FontFamily ?? string.Empty).Trim();
            if (!SafeFontName.IsMatch(fontFamily))
            {
                fontFamily = string.Empty;
            }

            string color = (item.Color ?? string.Empty).Trim();
            color = HexColor.IsMatch(color) ? color.ToUpperInvariant() : "#000000";

            var cleaned = new ImageTemplatePlaceholder
            {
                Id = id,
                Field = item.Field.Trim(),
                X = x,
                Y = y,
                Width = width,
                Height = height,
                Bold = item.Bold,
                Align = align,
                FontSize = fontSize,
                FontFamily = fontFamily,
                Color = color,
            };

            if (cleaned.IsValid)
            {
                result.Add(cleaned);
            }
        }

        return result;
    }

    /// <summary>The saved boxes, or an empty list if none were saved (or the file is unreadable — then nothing extra is printed).</summary>
    public static List<ImageTemplatePlaceholder> Load()
    {
        try
        {
            string path = GetFilePath();
            if (!File.Exists(path))
            {
                return new List<ImageTemplatePlaceholder>();
            }

            var items = JsonSerializer.Deserialize<List<ImageTemplatePlaceholder>>(File.ReadAllText(path));
            return Normalize(items);
        }
        catch (Exception ex)
        {
            AppLog.Error(LogCategory, "Could not read the saved image-template placeholders.", ex);
            return new List<ImageTemplatePlaceholder>();
        }
    }

    /// <summary>Writes <paramref name="placeholders"/> (already normalized) to disk, replacing any previous list. An empty list removes the file.</summary>
    public static void Save(IReadOnlyList<ImageTemplatePlaceholder> placeholders)
    {
        if (placeholders.Count == 0)
        {
            Clear();
            return;
        }

        File.WriteAllText(GetFilePath(), JsonSerializer.Serialize(placeholders));
        AppLog.Info(LogCategory, $"Saved {placeholders.Count} image-template placeholder(s).");
    }

    /// <summary>Removes every saved placeholder.</summary>
    public static void Clear()
    {
        try
        {
            string path = GetFilePath();
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
        catch (Exception ex)
        {
            AppLog.Error(LogCategory, "Could not remove the saved image-template placeholders.", ex);
        }
    }
}
